const japaneseDictionary = {
    "あなた(you)": "anata",
    "いえ(house)": "ie",
    "うみ(sea)": "umi",
    "えんぴつ(pencil)": "enpitsu",
    "おとこ(man)": "otoko",
    "かみ(hair)": "kami",
    "くるま(car)": "kuruma",
    "こども(child)": "kodomo",
    "さくらんぼ(cherry)": "sakuranbo",
    "しんぶん(newspaper)": "shinbun",
    "たけ(bamboo)": "take",
    "ちょう(butterfly)": "chou",
    "てがみ(letter)": "tegami",
    "にく(meat)": "niku",
    "ねこ(cat)": "neko",
    "はは(mother)": "haha",
    "ひと(person)": "hito",
    "みず(water)": "mizu",
    "もも(peach)": "momo",
    "ゆめ(dream)": "yume",
    "らいがっき(calendar)": "raigakki",
    "わたし(I, me)": "watashi",
    "がっこう(school)": "gakkou",
    "こうえん(park)": "kouen",
    "さんぽ(walk)": "sanpo",
    "へや(room)": "heya",
    "まんが(comic book)": "manga",
    "やさしい(easy)": "yasashii",
    "りんご(apple)": "ringo",
    "ひる(afternoon)": "hiru",
    "ばん(evening)": "ban",
    "あさ(morning)": "asa",
    "てんき(weather)": "tenki",
    "きょう(today)": "kyou",
    "あした(tomorrow)": "ashita",
    "きのう(yesterday)": "kinou",
    "さかな(fish)": "sakana",
    "みせ(shop)": "mise",
    "いぬ(dog)": "inu",
    "ことり(small bird)": "kotori",
    "はな(flower)": "hana",
    "そら(sky)": "sora",
    "やま(mountain)": "yama",
    "かわ(river)": "kawa",
    "もり(forest)": "mori",
    "ひかり(light)": "hikari",
    "ほし(star)": "hoshi",
    "つき(moon)": "tsuki",
    "たいよう(sun)": "taiyou",
    "おかね(money)": "okane",
    "とけい(clock)": "tokei",
    "ほん(book)": "hon",
    "でんわ(phone)": "denwa",
    "かばん(bag)": "kaban",
    "め(eye)": "me",
    "みみ(ear)": "mimi",
    "て(hand)": "te",
    "あし(leg)": "ashi",
    "くち(mouth)": "kuchi",
    "は(tooth)": "ha",
    "うた(song)": "uta",
    "おんがく(music)": "ongaku",
    "しゃしん(photo)": "shashin",
    "え(picture)": "e",
    "いす(chair)": "isu",
    "つくえ(desk)": "tsukue",
    "としょかん(library)": "toshokan",
    "びょういん(hospital)": "byouin",
    "えき(station)": "eki",
    "みち(road)": "michi",
    "くうこう(airport)": "kuukou",
    "ばしょ(place)": "basho",
    "まち(town)": "machi",
    "しろ(castle)": "shiro",
    "ホテル(hotel)": "hoteru",
    "レストラン(restaurant)": "resutoran",
    "たべもの(food)": "tabemono",
    "のみもの(drink)": "nomimono",
    "ごはん(meal)": "gohan",
    "パン(bread)": "pan",
    "みそしる(miso soup)": "misoshiru",
    "おちゃ(tea)": "ocha",
    "コーヒー(coffee)": "koohii",
    "さとう(sugar)": "satou",
    "しお(salt)": "shio",
    "こしょう(pepper)": "koshou",
    "さけ(sake)": "sake",
    "ぎゅうにく(beef)": "gyuuniku",
    "とりにく(chicken)": "toriniku",
    "ぶたにく(pork)": "butaniku",
    "さしみ(sashimi)": "sashimi",
    "すし(sushi)": "sushi",
    "てんぷら(tempura)": "tenpura",
    "うどん(udon noodles)": "udon",
    "そば(soba noodles)": "soba",
    "ラーメン(ramen)": "raamen",
    "カレー(curry)": "karee",
    "フルーツ(fruit)": "furuutsu",
    "いちご(strawberry)": "ichigo",
    "ばなな(banana)": "banana",
    "ぶどう(grape)": "budou",
    "すいか(watermelon)": "suika",
    "きゅうり(cucumber)": "kyuuri",
    "にんじん(carrot)": "ninjin",
    "たまねぎ(onion)": "tamanegi",
    "じゃがいも(potato)": "jagaimo",
    "はくさい(cabbage)": "hakusai",
    "れいぞうこ(refrigerator)": "reizouko",
    "テレビ(television)": "terebi",
    "コンピューター(computer)": "konpyuutaa",
    "カメラ(camera)": "kamera",
    "ラジオ(radio)": "rajio",
    "ゲーム(game)": "geemu",
    "スマートフォン(smartphone)": "sumaatofon",
    "じしょ(dictionary)": "jisho",
    "がっき(instrument)": "gakki",
    "でんき(electricity)": "denki",
    "でんしゃ(train)": "densha",
    "じてんしゃ(bicycle)": "jitensha",
    "バス(bus)": "basu",
    "タクシー(taxi)": "takushii",
    "ひこうき(airplane)": "hikouki",
    "ふね(boat)": "fune",
    "くつ(shoes)": "kutsu",
    "ぼうし(hat)": "boushi",
    "コート(coat)": "kooto",
    "シャツ(shirt)": "shatsu",
    "パンツ(pants)": "pantsu",
    "スカート(skirt)": "sukaato",
    "あか(red)": "aka",
    "あお(blue)": "ao",
    "しろ(white)": "shiro",
    "くろ(black)": "kuro",
    "きいろ(yellow)": "kiiro",
    "みどり(green)": "midori",
    "むらさき(purple)": "murasaki",
    "ピンク(pink)": "pinku",
    "ちゃいろ(brown)": "chairo",
    "オレンジ(orange)": "orenji"
};



function getRandomItem() {
    const keys = Object.keys(japaneseDictionary); // Get the keys of the object
    const randomKey = keys[Math.floor(Math.random() * keys.length)]; // Pick a random key
    return { word: randomKey, meaning: japaneseDictionary[randomKey] }; // Return the key and value
}

function randomWord() {
    const randomItem = getRandomItem();
    console.log(randomItem); // Log the random item
    document.getElementById("Answer").textContent = randomItem.meaning;
    document.getElementById("hiraganaTest").textContent = randomItem.word;
}