kanji_dict = {
    "の": "of, possessive particle / の / no",
    "に": "to, at, in / に / ni",
    "は": "topic particle / は / wa",
    "を": "direct object particle / を / wo",
    "と": "and, with / と / to",
    "が": "subject particle / が / ga",
    "で": "at, by, in / で / de",
    "も": "also, too / も / mo",
    "です": "is, polite copula / です / desu",
    "いる": "to be (animate) / いる / iru",
    "ある": "to be (inanimate) / ある / aru",
    "する": "to do, make / する / suru",
    "行く": "to go / いく / iku",
    "来る": "to come / くる / kuru",
    "見る": "to see / みる / miru",
    "聞く": "to ask, hear / きく / kiku",
    "食べる": "to eat / たべる / taberu",
    "飲む": "to drink / のむ / nomu",
    "話す": "to speak, talk / はなす / hanasu",
    "読む": "to read / よむ / yomu",
    "書く": "to write / かく / kaku",
    "買う": "to buy / かう / kau",
    "売る": "to sell / うる / uru",
    "見せる": "to show / みせる / miseru",
    "作る": "to make, create / つくる / tsukuru",
    "大きい": "big / おおきい / ookii",
    "小さい": "small / ちいさい / chiisai",
    "新しい": "new / あたらしい / atarashii",
    "古い": "old / ふるい / furui",
    "良い": "good / よい / yoi",
    "悪い": "bad / わるい / warui",
    "高い": "high, expensive / たかい / takai",
    "安い": "cheap / やすい / yasui",
    "長い": "long / ながい / nagai",
    "短い": "short / みじかい / mijikai",
    "楽しい": "fun, enjoyable / たのしい / tanoshii",
    "難しい": "difficult / むずかしい / muzukashii",
    "簡単": "easy, simple / かんたん / kantan",
    "早い": "fast, early / はやい / hayai",
    "遅い": "slow, late / おそい / osoi",
    "多い": "many / おおい / ooi",
    "少ない": "few / すくない / sukunai",
    "多分": "probably / たぶん / tabun",
    "時": "time, hour / とき / toki",
    "日": "day, sun / ひ / hi",
    "年": "year / とし / toshi",
    "月": "month, moon / つき / tsuki",
    "週": "week / しゅう / shuu",
    "今日": "today / きょう / kyou",
    "明日": "tomorrow / あした / ashita",
    "昨日": "yesterday / きのう / kinou",
    "今": "now / いま / ima",
    "前": "before, front / まえ / mae",
    "後": "after, behind / あと / ato",
    "上": "up, above / うえ / ue",
    "下": "down, below / した / shita",
    "左": "left / ひだり / hidari",
    "右": "right / みぎ / migi",
    "中": "middle, inside / なか / naka",
    "外": "outside / そと / soto",
    "北": "north / きた / kita",
    "南": "south / みなみ / minami",
    "東": "east / ひがし / higashi",
    "西": "west / にし / nishi",
    "今": "now / いま / ima",
    "大": "big / おお / oo",
    "小": "small / ちいさい / chiisai",
    "日本": "Japan / にほん / Nihon",
    "自分": "oneself / じぶん / jibun",
    "人": "person / ひと / hito",
    "子供": "child / こども / kodomo",
    "大人": "adult / おとな / otona",
    "友達": "friend / ともだち / tomodachi",
    "家": "house / いえ / ie",
    "学校": "school / がっこう / gakkou",
    "会社": "company / かいしゃ / kaisha",
    "仕事": "work / しごと / shigoto",
    "時間": "time / じかん / jikan",
    "お金": "money / おかね / okane",
    "言葉": "word / ことば / kotoba",
    "物": "thing, object / もの / mono",
    "意味": "meaning / いみ / imi",
    "場所": "place / ばしょ / basho",
    "料理": "cooking / りょうり / ryouri",
    "映画": "movie / えいが / eiga",
    "音楽": "music / おんがく / ongaku",
    "運転": "driving / うんてん / unten",
    "旅行": "travel / りょこう / ryokou",
    "天気": "weather / てんき / tenki",
    "車": "car / くるま / kuruma",
    "電車": "train / でんしゃ / densha",
    "自転車": "bicycle / じてんしゃ / jitensha",
    "仕事": "work / しごと / shigoto",
    "店": "store / みせ / mise",
    "部屋": "room / へや / heya",
    "道": "road / みち / michi",
    "道": "way, road / どう / dou",
    "友達": "friend / ともだち / tomodachi",
    "仕事": "job / しごと / shigoto",
    "食事": "meal / しょくじ / shokuji",
    "食べ物": "food / たべもの / tabemono",
    "飲み物": "drink / のみもの / nomimono",
    "問題": "problem / もんだい / mondai",
    "答え": "answer / こたえ / kotae",
    "理由": "reason / りゆう / riyuu",
    "考え": "thought / かんがえ / kangae",
    "気持ち": "feeling / きもち / kimochi",
    "頭": "head / あたま / atama",
    "目": "eye / め / me",
    "耳": "ear / みみ / mimi",
    "口": "mouth / くち / kuchi",
    "手": "hand / て / te",
    "足": "foot, leg / あし / ashi",
    "肩": "shoulder / かた / kata",
    "体": "body / からだ / karada",
    "心": "heart, mind / こころ / kokoro",
    "顔": "face / かお / kao",
    "目": "eye / め / me",
    "耳": "ear / みみ / mimi",
    "口": "mouth / くち / kuchi",
    "鼻": "nose / はな / hana",
    "涙": "tears / なみだ / namida",
    "汗": "sweat / あせ / ase",
    "指": "finger / ゆび / yubi",
    "腕": "arm / うで / ude",
    "足": "foot, leg / あし / ashi",
    "背": "back / せ / se",
    "声": "voice / こえ / koe",
    "音": "sound / おと / oto",
    "言葉": "word, language / ことば / kotoba",
    "話": "talk, conversation / はなし / hanashi",
    "事": "thing, matter / こと / koto",
    "目": "eye / め / me",
    "目": "target / め / me",
    "心": "heart, spirit / こころ / kokoro",
    "空": "sky / そら / sora",
    "雨": "rain / あめ / ame",
    "雪": "snow / ゆき / yuki",
    "風": "wind / かぜ / kaze",
    "火": "fire / ひ / hi",
    "水": "water / みず / mizu",
    "土": "earth, ground / つち / tsuchi",
    "大きい": "big / おおきい / ookii",
    "小さい": "small / ちいさい / chiisai",
    "新しい": "new / あたらしい / atarashii",
    "古い": "old / ふるい / furui",
    "良い": "good / よい / yoi",
    "悪い": "bad / わるい / warui",
    "高い": "high, expensive / たかい / takai",
    "安い": "cheap / やすい / yasui",
    "長い": "long / ながい / nagai",
    "短い": "short / みじかい / mijikai",
    "楽しい": "fun, enjoyable / たのしい / tanoshii",
    "難しい": "difficult / むずかしい / muzukashii",
    "簡単": "easy, simple / かんたん / kantan",
    "早い": "fast, early / はやい / hayai",
    "遅い": "slow, late / おそい / osoi",
    "多い": "many / おおい / ooi",
    "少ない": "few / すくない / sukunai",
    "多分": "probably / たぶん / tabun",
    "前": "before, front / まえ / mae",
    "後": "after, behind / あと / ato",
    "上": "up, above / うえ / ue",
    "下": "down, below / した / shita",
    "左": "left / ひだり / hidari",
    "右": "right / みぎ / migi",
    "中": "middle, inside / なか / naka",
    "外": "outside / そと / soto",
    "北": "north / きた / kita",
    "南": "south / みなみ / minami",
    "東": "east / ひがし / higashi",
    "西": "west / にし / nishi",
    "自分": "oneself / じぶん / jibun",
    "人": "person / ひと / hito",
    "子供": "child / こども / kodomo",
    "大人": "adult / おとな / otona",
    "友達": "friend / ともだち / tomodachi",
    "家": "house / いえ / ie",
    "学校": "school / がっこう / gakkou",
    "会社": "company / かいしゃ / kaisha",
    "仕事": "work / しごと / shigoto",
    "時間": "time / じかん / jikan",
    "お金": "money / おかね / okane",
    "言葉": "word / ことば / kotoba",
    "物": "thing, object / もの / mono",
    "意味": "meaning / いみ / imi",
    "場所": "place / ばしょ / basho",
    "料理": "cooking / りょうり / ryouri",
    "映画": "movie / えいが / eiga",
    "音楽": "music / おんがく / ongaku",
    "運転": "driving / うんてん / unten",
    "旅行": "travel / りょこう / ryokou",
    "天気": "weather / てんき / tenki",
    "車": "car / くるま / kuruma",
    "電車": "train / でんしゃ / densha",
    "自転車": "bicycle / じてんしゃ / jitensha",
    "店": "store / みせ / mise",
    "部屋": "room / へや / heya",
    "道": "road / みち / michi",
    "食事": "meal / しょくじ / shokuji",
    "食べ物": "food / たべもの / tabemono",
    "飲み物": "drink / のみもの / nomimono",
    "問題": "problem / もんだい / mondai",
    "答え": "answer / こたえ / kotae",
    "理由": "reason / りゆう / riyuu",
    "考え": "thought / かんがえ / kangae",
    "気持ち": "feeling / きもち / kimochi",
    "頭": "head / あたま / atama",
    "目": "eye / め / me",
    "耳": "ear / みみ / mimi",
    "口": "mouth / くち / kuchi",
    "手": "hand / て / te",
    "足": "foot, leg / あし / ashi",
    "肩": "shoulder / かた / kata",
    "体": "body / からだ / karada",
    "心": "heart, mind / こころ / kokoro",
    "顔": "face / かお / kao",
    "涙": "tears / なみだ / namida",
    "汗": "sweat / あせ / ase",
    "指": "finger / ゆび / yubi",
    "腕": "arm / うで / ude",
    "背": "back / せ / se",
    "声": "voice / こえ / koe",
    "音": "sound / おと / oto",
    "言葉": "word, language / ことば / kotoba",
    "話": "talk, conversation / はなし / hanashi",
    "事": "thing, matter / こと / koto",
    "空": "sky / そら / sora",
    "雨": "rain / あめ / ame",
    "雪": "snow / ゆき / yuki",
    "風": "wind / かぜ / kaze",
    "火": "fire / ひ / hi",
    "水": "water / みず / mizu",
    "土": "earth, ground / つち / tsuchi",
    "行く": "to go / いく / iku",
    "来る": "to come / くる / kuru",
    "見る": "to see / みる / miru",
    "食べる": "to eat / たべる / taberu",
    "飲む": "to drink / のむ / nomu",
    "話す": "to speak / はなす / hanasu",
    "書く": "to write / かく / kaku",
    "読む": "to read / よむ / yomu",
    "聞く": "to ask, listen / きく / kiku",
    "歩く": "to walk / あるく / aruku",
    "走る": "to run / はしる / hashiru",
    "待つ": "to wait / まつ / matsu",
    "寝る": "to sleep / ねる / neru",
    "起きる": "to wake up / おきる / okiru",
    "使う": "to use / つかう / tsukau",
    "買う": "to buy / かう / kau",
    "売る": "to sell / うる / uru",
    "遊ぶ": "to play / あそぶ / asobu",
    "作る": "to make / つくる / tsukuru",
    "勉強する": "to study / べんきょうする / benkyou suru",
    "働く": "to work / はたらく / hataraku",
    "教える": "to teach / おしえる / oshieru",
    "覚える": "to remember / おぼえる / oboeru",
    "忘れる": "to forget / わすれる / wasureru",
}

function getRandomItem() {
    const keys = Object.keys(kanji_dict); // Get the keys of the object
    const randomKey = keys[Math.floor(Math.random() * keys.length)]; // Pick a random key
    return { word: randomKey, meaning: kanji_dict[randomKey] }; // Return the key and value
}

function randomWord() {
    const randomItem = getRandomItem();
    console.log(randomItem); // Log the random item
    document.getElementById("Answer").textContent = randomItem.meaning;
    document.getElementById("hiraganaTest").textContent = randomItem.word;
}