const japaneseDictionary = {
    "あなた(you)": "anata",
    "いえ(house)": "ie",
    "うみ(sea)": "umi",
    "えんぴつ(pencil)": "enpitsu",
    "おとこ(man)": "otoko",
    "かみ(hair)": "kami",
    "くるま(car)": "kuruma",
    "こども(child)": "kodomo",
    "さくらんぼ(cherry)": "sakuranbo",
    "しろ(white)": "shiro",
    "すいか(watermelon)": "suika",
    "せんせい(teacher)": "sensei",
    "そら(sky)": "sora",
    "たべもの(food)": "tabemono",
    "ちず(map)": "chizu",
    "つき(moon)": "tsuki",
    "て(hand)": "te",
    "とけい(clock)": "tokei",
    "なつ(summer)": "natsu",
    "にほん(Japan)": "nihon",
    "ぬの(cloth)": "nuno",
    "ねこ(cat)": "neko",
    "のり(seaweed)": "nori",
    "はな(flower)": "hana",
    "ひと(person)": "hito",
    "ふじさん(Mt. Fuji)": "fujisan",
    "へび(snake)": "hebi",
    "ほし(star)": "hoshi",
    "まど(window)": "mado",
    "みず(water)": "mizu",
    "むし(insect)": "mushi",
    "め(eye)": "me",
    "もり(forest)": "mori",
    "やま(mountain)": "yama",
    "ゆき(snow)": "yuki",
    "ようふく(clothes)": "youfuku",
    "らいおん(lion)": "raion",
    "りんご(apple)": "ringo",
    "るす(absence)": "rusu",
    "れいぞうこ(refrigerator)": "reizouko",
    "ろうそく(candle)": "rousoku",
    "わたし(I)": "watashi",
    "を(meal object marker)": "wo",
    "ん(end)": "n",
    "あか(red)": "aka",
    "いぬ(dog)": "inu",
    "うた(song)": "uta",
    "えがお(smile)": "egao",
    "おんな(woman)": "onna",
    "かぜ(wind)": "kaze",
    "き(tree)": "ki",
    "くも(cloud)": "kumo",
    "けしごむ(eraser)": "keshigomu",
    "こうえん(park)": "kouen",
    "さかな(fish)": "sakana",
    "しんかんせん(bullet train)": "shinkansen",
    "すずめ(sparrow)": "suzume",
    "せかい(world)": "sekai",
    "そと(outside)": "soto",
    "たまご(egg)": "tamago",
    "ちかてつ(subway)": "chikatetsu",
    "つくえ(desk)": "tsukue",
    "てがみ(letter)": "tegami",
    "とり(bird)": "tori",
    "なみ(wave)": "nami",
    "にく(meat)": "niku",
    "ぬま(marsh)": "numa",
    "ねずみ(mouse)": "nezumi",
    "のう(farm)": "nou",
    "はし(bridge)": "hashi",
    "ひかり(light)": "hikari",
    "ふね(ship)": "fune",
    "へんじ(reply)": "henji",
    "ほたる(firefly)": "hotaru",
    "まち(town)": "machi",
    "みち(road)": "michi",
    "むら(village)": "mura",
    "めがね(glasses)": "megane",
    "もしもし(hello on phone)": "moshimoshi",
    "やさい(vegetable)": "yasai",
    "ゆうひ(sunset)": "yuuhi",
    "ようちえん(kindergarten)": "youchien",
    "らくだ(camel)": "rakuda",
    "りす(squirrel)": "risu",
    "るーる(rule)": "ru-ru",
    "れきし(history)": "rekishi",
    "ろく(six)": "roku",
    "わらい(laughter)": "warai",
    "いろ(color)": "iro",
    "うま(horse)": "uma",
    "えき(station)": "eki",
    "おちゃ(tea)": "ocha",
    "かさ(umbrella)": "kasa",
    "きつね(fox)": "kitsune",
    "くつ(shoes)": "kutsu",
    "けいさつ(police)": "keisatsu",
    "こえ(voice)": "koe",
    "さけ(salmon)": "sake",
    "しお(salt)": "shio",
    "すき(like)": "suki",
    "せき(seat)": "seki",
    "そば(buckwheat)": "soba",
    "たび(trip)": "tabi",
    "ちょう(butterfly)": "chou",
    "つばさ(wing)": "tsubasa",
    "てつ(iron)": "tetsu",
    "としょかん(library)": "toshokan",
    "ながれ(flow)": "nagare",
    "にわ(garden)": "niwa",
    "ねん(year)": "nen",
    "のこぎり(saw)": "nokogiri",
    "はっぱ(leaf)": "happa",
    "ひげ(beard)": "hige",
    "ふゆ(winter)": "fuyu",
    "へや(room)": "heya",
    "ほうせき(jewel)": "houseki",
    "まくら(pillow)": "makura",
    "みなみ(south)": "minami",
    "むこう(beyond)": "mukou",
    "めん(face)": "men",
    "もん(question)": "mon",
    "やき(skillet)": "yaki",
    "ゆうびん(mail)": "yuubin",
    "ようふく(clothes)": "youfuku",
    "らんぷ(lamp)": "ranpu",
    "りょう(hut)": "ryou",
    "るり(lapis lazuli)": "ruri",
    "れいす(lace)": "reis",
    "ろせん(bus route)": "rosen",
    "わん(dog bowl)": "wan",
    "ざる(basket)": "zaru",
    "しんゆう(best friend)": "shinyuu",
    "こい(love)": "koi",
    "うたごえ(singing voice)": "utagoe",
    "こうきょ(imperial palace)": "koukyo",
    "きのこ(mushroom)": "kinoko",
    "はんせい(reflection)": "hansei",
    "ぶんしょう(sentence)": "bunshou",
    "きんじょ(neighborhood)": "kinjo",
    "てんき(weather)": "tenki",
    "れいぞう(refrigeration)": "reizou",
    "かぎ(key)": "kagi",
    "しゅくだい(homework)": "shukudai",
    "じしん(earthquake)": "jishin",
    "とくてい(specific)": "tokutei",
    "せいと(student)": "seito",
    "じゅぎょう(lesson)": "jugyou",
    "えほん(picture book)": "ehon",
    "こうどう(behavior)": "koudou",
    "かんじ(chinese character)": "kanji",
    "ほこうしゃ(pedestrian)": "hokousha",
    "さばく(desert)": "sabaku",
    "きょうかしょ(textbook)": "kyoukasho",
    "じてんしゃ(bicycle)": "jitensha",
    "ねぼう(oversleep)": "nebou",
    "みかん(mandarin orange)": "mikan",
    "ひるやすみ(lunch break)": "hiruyasumi",
    "あんぜん(safety)": "anzen",
    "のぞみ(hope)": "nozomi",
    "うらやましい(jealous)": "urayamashii",
    "けんこう(health)": "kenkou",
    "はなぢ(nosebleed)": "hanaji",
    "じかん(time)": "jikan",
    "めいじん(master)": "meijin",
    "かいじょう(venue)": "kaijou",
    "ふんすい(fountain)": "funsui",
    "ふくろう(owl)": "fukurou",
    "てんし(angel)": "tenshi",
    "ぎんこう(bank)": "ginkou",
    "とけいかい(counterclockwise)": "tokeikai",
    "しゅくさい(festival)": "shukusai",
  "あなた(you)": "anata",
    "いえ(house)": "ie",
    "うみ(sea)": "umi",
    "えんぴつ(pencil)": "enpitsu",
    "おとこ(man)": "otoko",
    "かみ(hair)": "kami",
    "くるま(car)": "kuruma",
    "こども(child)": "kodomo",
    "さくらんぼ(cherry)": "sakuranbo",
    "しんぶん(newspaper)": "shinbun",
    "たけ(bamboo)": "take",
    "ちょう(butterfly)": "chou",
    "てがみ(letter)": "tegami",
    "にく(meat)": "niku",
    "ねこ(cat)": "neko",
    "はは(mother)": "haha",
    "ひと(person)": "hito",
    "みず(water)": "mizu",
    "もも(peach)": "momo",
    "ゆめ(dream)": "yume",
    "らいがっき(calendar)": "raigakki",
    "わたし(I, me)": "watashi",
    "がっこう(school)": "gakkou",
    "こうえん(park)": "kouen",
    "さんぽ(walk)": "sanpo",
    "へや(room)": "heya",
    "まんが(comic book)": "manga",
    "やさしい(easy)": "yasashii",
    "りんご(apple)": "ringo",
    "ひる(afternoon)": "hiru",
    "ばん(evening)": "ban",
    "あさ(morning)": "asa",
    "てんき(weather)": "tenki",
    "きょう(today)": "kyou",
    "あした(tomorrow)": "ashita",
    "きのう(yesterday)": "kinou",
    "さかな(fish)": "sakana",
    "みせ(shop)": "mise",
    "いぬ(dog)": "inu",
    "ことり(small bird)": "kotori",
    "はな(flower)": "hana",
    "そら(sky)": "sora",
    "やま(mountain)": "yama",
    "かわ(river)": "kawa",
    "もり(forest)": "mori",
    "ひかり(light)": "hikari",
    "ほし(star)": "hoshi",
    "つき(moon)": "tsuki",
    "たいよう(sun)": "taiyou",
    "おかね(money)": "okane",
    "とけい(clock)": "tokei",
    "ほん(book)": "hon",
    "でんわ(phone)": "denwa",
    "かばん(bag)": "kaban",
    "め(eye)": "me",
    "みみ(ear)": "mimi",
    "て(hand)": "te",
    "あし(leg)": "ashi",
    "くち(mouth)": "kuchi",
    "は(tooth)": "ha",
    "うた(song)": "uta",
    "おんがく(music)": "ongaku",
    "しゃしん(photo)": "shashin",
    "え(picture)": "e",
    "いす(chair)": "isu",
    "つくえ(desk)": "tsukue",
    "としょかん(library)": "toshokan",
    "びょういん(hospital)": "byouin",
    "えき(station)": "eki",
    "みち(road)": "michi",
    "くうこう(airport)": "kuukou",
    "ばしょ(place)": "basho",
    "まち(town)": "machi",
    "しろ(castle)": "shiro",
    "ホテル(hotel)": "hoteru",
    "レストラン(restaurant)": "resutoran",
    "たべもの(food)": "tabemono",
    "のみもの(drink)": "nomimono",
    "ごはん(meal)": "gohan",
    "パン(bread)": "pan",
    "みそしる(miso soup)": "misoshiru",
    "おちゃ(tea)": "ocha",
    "コーヒー(coffee)": "koohii",
    "さとう(sugar)": "satou",
    "しお(salt)": "shio",
    "こしょう(pepper)": "koshou",
    "さけ(sake)": "sake",
    "ぎゅうにく(beef)": "gyuuniku",
    "とりにく(chicken)": "toriniku",
    "ぶたにく(pork)": "butaniku",
    "さしみ(sashimi)": "sashimi",
    "すし(sushi)": "sushi",
    "てんぷら(tempura)": "tenpura",
    "うどん(udon noodles)": "udon",
    "そば(soba noodles)": "soba",
    "ラーメン(ramen)": "raamen",
    "カレー(curry)": "karee",
    "フルーツ(fruit)": "furuutsu",
    "いちご(strawberry)": "ichigo",
    "ばなな(banana)": "banana",
    "ぶどう(grape)": "budou",
    "すいか(watermelon)": "suika",
    "きゅうり(cucumber)": "kyuuri",
    "にんじん(carrot)": "ninjin",
    "たまねぎ(onion)": "tamanegi",
    "じゃがいも(potato)": "jagaimo",
    "はくさい(cabbage)": "hakusai",
    "れいぞうこ(refrigerator)": "reizouko",
    "テレビ(television)": "terebi",
    "コンピューター(computer)": "konpyuutaa",
    "カメラ(camera)": "kamera",
    "ラジオ(radio)": "rajio",
    "ゲーム(game)": "geemu",
    "スマートフォン(smartphone)": "sumaatofon",
    "じしょ(dictionary)": "jisho",
    "がっき(instrument)": "gakki",
    "でんき(electricity)": "denki",
    "でんしゃ(train)": "densha",
    "じてんしゃ(bicycle)": "jitensha",
    "バス(bus)": "basu",
    "タクシー(taxi)": "takushii",
    "ひこうき(airplane)": "hikouki",
    "ふね(boat)": "fune",
    "くつ(shoes)": "kutsu",
    "ぼうし(hat)": "boushi",
    "コート(coat)": "kooto",
    "シャツ(shirt)": "shatsu",
    "パンツ(pants)": "pantsu",
    "スカート(skirt)": "sukaato",
    "あか(red)": "aka",
    "あお(blue)": "ao",
    "しろ(white)": "shiro",
    "くろ(black)": "kuro",
    "きいろ(yellow)": "kiiro",
    "みどり(green)": "midori",
    "むらさき(purple)": "murasaki",
    "ピンク(pink)": "pinku",
    "ちゃいろ(brown)": "chairo",
    "オレンジ(orange)": "orenji"
};

function getRandomItem() {
    const keys = Object.keys(japaneseDictionary); // Get the keys of the object
    const randomKey = keys[Math.floor(Math.random() * keys.length)]; // Pick a random key
    return { word: randomKey, meaning: japaneseDictionary[randomKey] }; // Return the key and value
}

function randomWord() {
    const randomItem = getRandomItem();
    console.log(randomItem); // Log the random item
    document.getElementById("Answer").textContent = randomItem.meaning;
    document.getElementById("hiraganaTest").textContent = randomItem.word;
}